apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsdbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awsdbuggy
  template:
    metadata:
      labels:
        app: awsdbuggy
    spec:
      containers:
      - name: awsdbuggy
        image: 975049920961.dkr.ecr.ap-southeast-2.amazonaws.com/awsd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: awsdbuggy
    k8s-app: awsdbuggy
  name: awsdbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: awsdbuggy
